# Site settings
title: "jeffrangel"
bye_message: ""
baseurl: "/"
url: "https://jeffrangel.com"

# Header settings
nick: "jeffrangel"
mail:
    domain: "jeffrangel"
    ext: "com"
source_code:
    server: "github.com"
    nick: "jeffrangel"
fingerprint_key: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title/
