# Site settings
title: "jeffrangel"
bye_message: ""
baseurl: "/"
url: "https://jeffrangel.com"

# Header settings
nick: "jeffrangel"
mail:
    domain: "jeffrangel"
    ext: "com"
source_code:
    server: "github.com"
    nick: "jeffrangel"
fingerprint_key: "2586 6065 2323 EDC5 B95E 8155 E4E7 2AF5 F127 257A"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
